### ISSUE TITLE
Build error since commit https://github.com/xtknight/mt7610u-linksys-ae6000-wifi-fixes/commit/36798fee666621b2e5d94d40a9072a756b9b372f

### ISSUE THREAD

**Issue by mkreisl** [xtknight/mt7610u-linksys-ae6000-wifi-fixes#23]
Can not build module since this commit https://github.com/xtknight/mt7610u-linksys-ae6000-wifi-fixes/commit/36798fee666621b2e5d94d40a9072a756b9b372f

**Comment by xtknight** [comment]
Please test new master and close if no issue. You had mentioned 4.12.x had a problem as well? Although I noticed that this structure was introduced in 4.8.

**Comment by mkreisl** [comment]
Already told that 4.12 is ok, was my fault

Build of kernel 4.4.x works again, thanks for your fast response
