### ISSUE TITLE
does not build on ubuntu xenial with linux-image-generic-hwe-16.04-edge (kernel 4.13) - fix included

### ISSUE THREAD

**Issue by mailinglists35** [xtknight/mt7610u-linksys-ae6000-wifi-fixes#30]
I got this asus ac-51

````Bus 001 Device 006: ID 0b05:17d1 ASUSTek Computer, Inc. AC51 802.11a/b/g/n/ac Wireless Adapter [Mediatek MT7610U]````

trying to compile barfs with 

````
                 from /usr/local/src/mt7610u-linksys-ae6000-wifi-fixes/os/linux/../../os/linux/sta_ioctl.c:30:
In function ‘memcpy’,
    inlined from ‘rt_ioctl_iwaplist’ at /usr/local/src/mt7610u-linksys-ae6000-wifi-fixes/os/linux/../../os/linux/sta_ioctl.c:696:2:
./include/linux/string.h:305:4: error: call to ‘__read_overflow2’ declared with attribute error: detected read beyond size of object passed as 2nd parameter
    __read_overflow2();
    ^
scripts/Makefile.build:302: recipe for target '/usr/local/src/mt7610u-linksys-ae6000-wifi-fixes/os/linux/../../os/linux/sta_ioctl.o' failed
make[2]: *** [/usr/local/src/mt7610u-linksys-ae6000-wifi-fixes/os/linux/../../os/linux/sta_ioctl.o] Error 1
Makefile:1546: recipe for target '_module_/usr/local/src/mt7610u-linksys-ae6000-wifi-fixes/os/linux' failed
make[1]: *** [_module_/usr/local/src/mt7610u-linksys-ae6000-wifi-fixes/os/linux] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.13.0-19-generic'
Makefile:394: recipe for target 'LINUX' failed
make: *** [LINUX] Error 2
````

googling for that error leads me to an [archlinux thread](https://bbs.archlinux.org/viewtopic.php?id=231434) which in turn one of the replies references a [small modification of sta_ioctl.c](https://github.com/genodeftest/Netgear-A6210/commit/dc7e9b8c44815eb20ebef683641f94da6732be71) that makes it comply with kernel 4.13

Hoping this will help others, I don't know how to submit a PR, you just need to delete that ampersand symbol at line 549 in sta_ioctl.c and it will build.

**Comment by galvanized** [comment]
#31

**Comment by xtknight** [comment]
Thanks for reporting ~ I have merged the PR. Please reopen if bug resurfaces.
