### ISSUE TITLE
wifi signal 0

### ISSUE THREAD

**Issue by liuhangcheng** [xtknight/mt7610u-linksys-ae6000-wifi-fixes#9]
there is a ssid list in the network manager,but all of them has signal 0, and i cant connect, my system is Ubuntu 16.04 lts

**Comment by na-ji** [comment]
Same problem here (+ crash when trying to connect), did you solve it @liuhangcheng?

**Comment by liuhangcheng** [comment]
https://github.com/ulli-kroll/mt7610u
